### ISSUE TITLE
Ошибки значения параметра Value

### ISSUE THREAD

**Issue by d4rxt4r** [h10ne/VkPlayer#10]
Странные ошибки сегодня полезли
![image](https://user-images.githubusercontent.com/7714963/54767951-48233c80-4c0f-11e9-9410-a23994fc39d8.png)

**Comment by h10ne** [comment]
> Странные ошибки сегодня полезли
> ![image](https://user-images.githubusercontent.com/7714963/54767951-48233c80-4c0f-11e9-9410-a23994fc39d8.png)

При каких обстоятельствах такое бывает?

**Comment by d4rxt4r** [comment]
Как только включаю воспроизведение

upd. Только что проверил, ошибок больше нет, компьютер не перезагружался. Магия （｡･ω･｡)つ━☆・*。

**Comment by h10ne** [comment]
Значит можно закрывать))

**Comment by h10ne** [comment]
Значит можно закрывать)
